stages:
  - build
  - publish

variables:
  GIT_DEPTH: 0 # clone all

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

build:
  stage: build
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/
  script:
    - ./gradlew build
  artifacts:
    paths:
      - 'build/libs/*.jar'
    expire_in: 1 week

publish:
  stage: publish
  only:
    - branches
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .gradle/
    policy: pull
  script:
    - './gradlew curseforge'

