stages:
  - build
  - publish

variables:
  GIT_DEPTH: 0 # clone all

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .gradle/
    - build/
  policy: pull-push

build:
  stage: build
  script:
    - ./gradlew build
  artifacts:
    paths:
      - 'build/libs/*.jar'
    expire_in: 1 week
  except:
    - tags

publish:
  stage: publish
  cache:
    <<: *global_cache
    policy: pull
  script:
    - './gradlew curseforge'
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^\d\.\d{1,3}(?:\.(?:\d{1,3}|x))?$/'
      when: always
    - when: never
