modLoader="javafml"
loaderVersion="${fml_version_range}"
license="GNU GPLv3"
issueTrackerURL="https://github.com/percivalalb/MapMakingTools/issues"
displayURL="https://minecraft.curseforge.com/projects/map-making-tools/"
logoFile="mmt_logo.png"
[[mods]]
    modId="mapmakingtools"
    version="${version}"
    updateJSONURL="https://www.dropbox.com/s/raw/1mlp6d42h3k65tx/version-mapmakingtools.json"
    displayName="Map Making Tools"
    credits="percivalalb"
    authors="percivalalb"
    description='''Map Making Tools'''
[[dependencies.doggytalents]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.doggytalents]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
